services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=catalog
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth=md5

      - DB_HOST=localhost
      - DB_USER=catalog
      - DB_PASSWORD=password
      - DB_NAME=postgres
      - DB_PORT=15432
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: